[project]
name = "erddap-mcp-demo"
version = "0.1.0"
description = "Model Context Protocol demo project for ERDDAP"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.6.0",
]
